[MDH-152] feat & test : 메뉴 카테고리 도메인 추가
prgrms-be-devcourse/BE-04-DevTable pull request #68
Opened 2023-09-11 09:56 UTC by joyfulviper

## 🖊️ 1. Changes

-

## 🖼️ 2. Screenshot

-

## ❗️ 3. Issues

1. 
2. 

## 😌 4. To Reviewer

- db 스키마와 동일하게 작성했습니다. menuType, mealType은 enum이 아닌 String으로 작성했는데 굳이 제약을 두는 것 보다는 자유롭게 열어 둬도 무방하다고 생각했습니다~

2023-09-11 10:30 UTC, heenahan commented on src/main/java/com/mdh/devtable/menu/domain/MenuCategory.java
> +    @Column(name = "description", length = 63)
nullable = true여도 명시해주면 좋을 것 같아요!! 
다른 엔티티에서는 다 명시해주기도 했고 빼먹고 안쓰신 건지 실제로 true인지 다른 사람이 볼 땐 알기 어려우니까요..!!

2023-09-11 10:30 UTC, heenahan commented on src/main/java/com/mdh/devtable/menu/domain/MenuCategory.java
> +    private String menuType;
타입의 경우 enum으로 안 만들어주시나요??

2023-09-11 10:31 UTC, heenahan commented on src/main/java/com/mdh/devtable/menu/domain/MenuCategory.java
> +    private String mealType;
이것도 enum으로 안만드시나요??

2023-09-11 11:41 UTC, joyfulviper commented on src/main/java/com/mdh/devtable/menu/domain/MenuCategory.java
> +    private String menuType;
아뇨 이거 가능성을 다 열어뒀어요 너무 제약하면 코드 작성할 것도 많아지고 딱히 검증하지 않아도 문제 안될 것 같아서여! 무엇보다 제약을 두면 확장에 너무 불리해서..

2023-09-11 11:42 UTC, joyfulviper commented on src/main/java/com/mdh/devtable/menu/domain/MenuCategory.java
> +    private String mealType;
네네 위 사항과 동일합니다~! 점주용 어플을 사용해보지는 않았는데 굳이 enum으로 제한을 둘 필요는 없을 것 같아서 ㅋㅋㅋㅋ..

2023-09-11 11:42 UTC, joyfulviper commented on src/main/java/com/mdh/devtable/menu/domain/MenuCategory.java
> +    @Column(name = "description", length = 63)
넵넵!

2023-09-11 12:11 UTC, bombo-dev commented on src/main/java/com/mdh/devtable/menu/domain/MenuCategory.java
> +    private String menuType;
이전에 코멘트 달아두었는데, menu_type이나 meal_type을 열어두면 저희가 조회하는데 오히려 더 어려워 질 수 있는 문제가 있어요.
enum으로서의 확장으로 인해 재 배포에 대한 문제를 고려하신다면 테이블로 분리를 해야 합니다

2023-09-11 12:33 UTC, heenahan commented on src/main/java/com/mdh/devtable/menu/domain/MenuCategory.java
> +    private String menuType;
종운님 의견에 동의하는게 menu_type이나 meal_type을 이용해 점심과 저녁의 최소 최대 가격을 계산할 것이기 때문에 저희가 원하는 값 외에 다른 값이 들어오면 안될 것 같아요!!

2023-09-11 14:33 UTC, bombo-dev commented on src/main/java/com/mdh/devtable/menu/persentation/dto/MenuCategoryCreateRequest.java
> +        String description,
@Length(63)이 빠진 것 같아요

2023-09-11 14:48 UTC, joyfulviper commented on src/main/java/com/mdh/devtable/menu/persentation/dto/MenuCategoryCreateRequest.java
> +        String description,
넵

2023-09-11 14:53 UTC, bombo-dev requested changes

2023-09-11 14:53 UTC, bombo-dev commented on src/main/java/com/mdh/devtable/menu/application/MenuCategoryService.java
> +        menuCategoryRepository.save(menuCategoryCreateRequest.toEntity(shopId));
save() 내에 들어가는 값에 대해서 밖으로 꺼내놓는게 좋다고 피드백을 받은 적이 있습니다!

2023-09-11 14:53 UTC, bombo-dev commented on src/main/java/com/mdh/devtable/menu/domain/MealType.java
> +
@Getter가 있어야 name에 접근 할 수 있을 것 같아요

2023-09-11 14:53 UTC, bombo-dev commented on src/main/java/com/mdh/devtable/menu/domain/MenuCategory.java
> +    public void updateMenuCategory(String name,
해당 카테고리의 minPrice와 maxPrice는 생성 시에 결정되지 않고 Category가 가지고 있는 Menu들의 가격에 따라 결정되서 minPrice와 maxPrice는 업데이트에서 제외하는 게 좋을 것 같아요.

2023-09-11 14:53 UTC, bombo-dev commented on src/main/java/com/mdh/devtable/menu/domain/MenuType.java
> +
동일하게 @Getter가 없어서 필드에 접근 할 수 없겠네요.

2023-09-11 14:53 UTC, bombo-dev commented on src/test/java/com/mdh/devtable/ownerwaiting/presentaion/controller/OwnerWaitingControllerTest.java
> +                .andExpect(status().isOk())
andExpect(status())가 두 개 있네요.

2023-09-11 15:45 UTC, joyfulviper commented on src/test/java/com/mdh/devtable/ownerwaiting/presentaion/controller/OwnerWaitingControllerTest.java
> +                .andExpect(status().isOk())
넵 수정할게용

2023-09-12 04:26 UTC, bombo-dev commented on src/main/java/com/mdh/devtable/menu/domain/MenuCategory.java
> +    private Long version;
버전 추가를 변경 점에 추가해주셨으면 좋을 것 같아요~

2023-09-12 04:27 UTC, bombo-dev approved these changes

2023-09-12 04:27 UTC, heenahan approved these changes

2023-09-12 14:40 UTC, closed without merging